export { default as RegistTosScreen } from './RegistTosScreen'
export { default as RegistTosDetailScreen } from './RegistTosDetailScreen'
export { default as RegistGenderScreen } from './RegistGenderScreen'
export { default as RegistCalendarScreen } from './RegistCalendarScreen'
export { default as RegistAverageScreen } from './RegistAverageScreen'
export { default as RegistInviteScreen } from './RegistInviteScreen'
export { default as BoardingScreen } from './BoardingScreen'